### ISSUE TITLE
Suggestions!

### ISSUE THREAD

**Issue by Hexer10** [Timocop/BasicPawn#11]
Hi,

First I'd like to have autocomplete for the forwards I mean:

![AutoCompleteForward](http://csitajb.it/images/CompileForward.gif)

Second, I think would be nice to have the natives/forward syntax even in brackets:

![AlwaysInfo](http://csitajb.it/images/AlwaysInfo.gif)

Third, Idk if it's possibile but would be nice to have the syntax of forwards Hooked with HookEvent (or SdkHook?, Reg*Cmd?):

![AutoCompleteHook](http://csitajb.it/images/HookCompile.gif)

Fourth, add the possibility to  "separate a from the window":

![TwoWindows](http://csitajb.it/images/TwoWindowsFix.gif)

Fifth, make an auto-upload via FTP(/SFTP)

And last, make in the configs an option to set custom compiler options.
BTW, nice editor!

PS; I wrote wrong it's "autocomplete" not "autocompile".

**Comment by Timocop** [comment]
Thanks for the detailed feedback!
This reminds me of creating a wiki how to use BasicPawn, some features are a bit hidden :P.

1.) You can autocomplete forwards, but the line must be empty/whitespace (only the name of the forward) then it will fully autocomplete. Otherwise it will just autocomplete the name.
![](https://i.imgur.com/Rntdzt0.gif)

2.) You need to put it into a scope for that to work (For performance reasons).
![](https://i.imgur.com/8YGw3ab.gif)

3.) Autocompletion of callbacks is also supported, just a bit different than you mentioned. Its like 1) but you have to write the tag of the callback argument instead. For example to autocomplete the callback of `RegConsoleCmd()` you have to write `ConCmd` because it has `ConCmd:callback` as argument.
![](https://i.imgur.com/vbOOf6A.gif)

4.) You can Popout tabs. More Drag&Drop support is on my Todo list.
![](https://i.imgur.com/Rr1GFc4.gif)

5.) On my Todo list already. But as a plugin not as a main build-in feature.

6.) You have to use BasicPawn Shell for custom compiler options. But ill add that on my todo list too.
![](https://i.imgur.com/jEzQEdC.png)

Ill leave this open for now, for the todo stuff. I hope that helped! :)

**Comment by Hexer10** [comment]
Thanks for the reply!

Also is it possible to chage the default "open directory", I mean, I keep all my .sp files in D:\...\...
Not in D:\Documents\ to it's possible to change that directory?

**Comment by Timocop** [comment]
What "Open Directory" do you mean?
---
Those are just Copy&Paste examples as stated ![here](https://github.com/Timocop/BasicPawn/blob/master/LICENSE#L623), i could remove it but it was part of the GitHub license template so i left it there.

**Comment by Hexer10** [comment]
Sorry, I mean when I go to: 
File > Open
It by default go to: Documents folder.
Can it be changed?

**Comment by Hexer10** [comment]
And I suggest to return to "wrap around" like notepad++ when reached the end of the file while searching

**Comment by Timocop** [comment]
Windows should keep the last path that you opened by default, unless you have some cleaner running in the background that removes the cache. On my end it works fine.
Btw. You can also Drag&Drop files onto BasicPawn or accociate file types in the settings. Its way easier that way.

"Warp around" also exist, its called "Loop search".

**Comment by Timocop** [comment]
All done.
FTP Plugin is released [here](https://github.com/Timocop/BasicPawn/tree/master/Plugin%20Releases).
