### ISSUE TITLE
Format Code

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#20]
Would be good if there was hotkeys (**Ctrl+R** for current tab and **Ctrl+Shift+R** for all tabs) for Format Code feature (and support for all content without need to select where to format).

Also there something strange (bug?) with autoclose feature. This works **ALWAYS** even if you do it inside variable name. I think that this should work only if there is no text around.

**Comment by Timocop** [comment]
Ive added hotkeys and support to format all content without selecting anything.
Ctrl+R to format code.
Ctrl+T to trim ending whitespace.

I scraped the idea of formating all tabs, because the TextEditor events are disabled while they are in the background. So editing tabs content in the background could glitch some UI parts of the program. Since you have to edit active tabs only, looping though tabs activating and formating them just looks bad. 
Also it seems quite *unsafe* to edit all tabs though a hotkey. For example if you accedently hit the hotkey and you format all opened tabs but you didnt wanted to.

And yes the autoclose feature always works.

**Comment by MAGNAT2645** [comment]
I also thought about it after reading about SharpDeveloper TextEditor features.
I do not know why I suggested to add formatting for all the tabs. Usually when there is one function, many developers add support to work for all the content (in this case, tabs) at once.

And about auto-closing, it's inconvenient to use (after using other text editors with same feature). When I need to write a lot of strings, the second quote appears every time and the extra quotes have to be deleted manually.

**Comment by Timocop** [comment]
The autoclose feature is pretty new and need some work still. You can disable it in the settings.
