### ISSUE TITLE
Didn't ask if I want to save unsaved files on update

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#27]
BasicPawn didn't ask if I want to save my unsaved files when clicking "Update and Exit" button in update window, it just closes BasicPawn and all files left unsaved. I understand that this is may sound dumb cuz I'm clicking "Update and **Exit**" but I think it still should ask if I want to save my files or not.

**Comment by GAMMACASE** [comment]
Alright, now I see message that my unsaved files will be lost when update is downloading, but why it can't just show dialog window that asks if I want to save my files?

**Comment by Timocop** [comment]
The reason why i didnt add a save dialog is because it would only affect the main instance, not other BasicPawn instances running in the background. People would assume its saved on all instances before the background instances are being killed in order to replace files, which isnt the case.

I could add some communication between the instances to promt save dialogs but i think its unessescary. A big fat warning should be enough to warn the user to save their files.

**Comment by GAMMACASE** [comment]
hmm, yeah a warning should be also okay, cuz rn that text that says that your files will not be saved isn't noticeable well.

**Comment by Timocop** [comment]
Done. Added a warning when trying to update.
