### ISSUE TITLE
Don't shift one-line functions

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#38]
Autoformat always shifts one-line ( without { } ) functions (and not only functions, can be also inside loops). Would be better if autoformat will not touch it.
![eb](https://user-images.githubusercontent.com/11666918/51087166-2fab2780-1771-11e9-99d9-4f08467c02a5.png)

And some from GitHub:
![eb](https://user-images.githubusercontent.com/11666918/51087200-c37cf380-1771-11e9-80cb-6b0e386ee7db.png)

**Comment by Timocop** [comment]
I think leaving lines out will confuse users more than wrong indention. Currently, reidention is pretty basic (Just like Notepad++) and has some non-context aware checks. I will improve it in the future however.

For now if your source is complex (like the screenshots you posted) just format code at selected lines instead of the whole project.

**Comment by Timocop** [comment]
Single-line function reindentions are intentional. However there was an issue escaped-newlines on preprocessor directives (``\\n``). Fixed that. Preprocessor directives should now reindented correctly.
I also removed reindention after statements. Always behaved quite dumb since it only checked one line (like your example in the picture at the bottom). eg formating:
```SourcePawn
if(a)
    if(b)
        if(c)
        {
            c = 0;
        }
```
will result in:
```SourcePawn
if(a)         //Indention = Scope-depth
    if(b)     //Indention = Scope-depth + if^
    if(c)     //Indention = Scope-depth + if^
{
    c = 0;
}
```
and now it results in:
```SourcePawn
if(a)
if(b)
if(c)
{
    c = 0;
}
```
just like Notepad++.

**Comment by MAGNAT2645** [comment]
Is that normal behavior to autoformat?

![default](https://user-images.githubusercontent.com/11666918/51908415-a12edb00-23eb-11e9-8cc4-2ec42aa03b0f.png)

**Comment by Timocop** [comment]
Yes. I removed the after-statement shift. It was quite buggy if used with multiple statements, explained above. Now it works like Notepad++'s format code.

**Comment by Timocop** [comment]
I will bring it back eventualy. But im not using the old system for that nor do i bring the old thing back. But you can use an older BasicPawn version to still format your code like that. But youll have to wait a little while for the new system.
