### ISSUE TITLE
Struct (not enum struct) variables are marked with macros colors

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#44]
Here's pic of how it looks like:
![image](https://user-images.githubusercontent.com/31375974/52104190-618a0e00-25fa-11e9-895c-8fabedc88d66.png)
``myinfo`` here has color of macros defines, but it's just a variable name (Am I right?) of type Plugin which is ``struct``, that struct definition can be found in sourcemod.inc file. So I think that it should have white color like other variable names have(In vs2017 dark theme at least, not sure how it is in other styles).

**Comment by Timocop** [comment]
Yes youre right. Back in the day i colored `public` and `struct` like defines since most people use them for read-only things like initalizing arrays or use them in loops. Since they are colored differently user whould know they are more 'important' than just variables or work like defines.
I guess we can change it?

**Comment by GAMMACASE** [comment]
I guess so, you can't really use that struct other than define it, but it's still a variable, so no need for it to be colored as macros define.

**Comment by Timocop** [comment]
I made it optional now. Since people requested this feature back.
