### ISSUE TITLE
Sometimes autocompletion does not work.

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#62]
Sadly I can't find way to constantly repeat that issue, but the main thing you need to do is to try autocomplete anything new that you didn't autocomplete in current file, and at some point you will be unable to do so or if you have some files included you will be redirected to that file to some random line in it, also if you move that include to somewhere else you'll get an error that that file was not found once you hit that problem again. Fix for that would be clicking away (even in the same file) and come back to that line, and now you can do autocompletion. Can't actually record any gif showing this cuz as I said I don't know how to reproduce that and I'm hitting that bug constantly while using autocomplete, and when I hit that bug I need to press record to actually record that gif which leads to clicking away from that line that fixes that issue on that autocomplete. Here's what I managed to record, here I hit that bug and get error about missing file, but then again as I said it fixed itself when I clicked away from it. 
![MvHIfeDmaO](https://user-images.githubusercontent.com/31375974/58024290-80190400-7b1a-11e9-8750-6200925bd5a2.gif)
Hope it'll give you some clue on what it can be, cuz it's really annoying especially when it redirects you to some line somewhere in different file.

**Comment by Timocop** [comment]
Since v0.830 the autocompletion and information details tabs share the same keyboard shortcuts (See: `Help > Special Controls`). Depends wich one is selected.  This could explain why clicking in the text editor solves the problem. Since clicking on a word in the text editor will select the autocompletion details tab automatically. Also the "Unable to open path" message box is from the information tab. https://github.com/Timocop/BasicPawn/blob/2955766fd4b4483dab589c22b0ae2a444ae8d482/BasicPawn/Controls%20and%20Forms/Main/UCInformationList.vb#L243

Are you sure you're not hitting `Ctrl+Enter` in the information tab on accident?
Did this happen before v0.830 too?

I'll investigate this further.

**Comment by GAMMACASE** [comment]
Yep, looks like it, when I'm trying to use ctrl+enter on information tab it doing all these things I was describing, but then I don't understand why it's not switching me to autocomplete and intellisense tab even tho I have auto switch to that tab checked in settings.

**Comment by Timocop** [comment]
I've made a commit (4d16fa41bfc118a1ac751c8383886ac38ede7061) that switches automatically to the autocomplete tab while you're writing. If you want to switch between the autocomplete or information tab manualy (without using the mouse), use the keyboard shortcuts `Ctrl+Alt+Left`/`Ctrl+Alt+Right`.

You can test it out if you want and tell me if you like the change :)

**Comment by GAMMACASE** [comment]
Can't really test it as much I as I want to rn, but at a first look it feels alright

**Comment by GAMMACASE** [comment]
Alright, tested it for a long time already, do not have any troubles since then.
