### ISSUE TITLE
Add Lysis support

### ISSUE THREAD

**Issue by MAGNAT2645** [Timocop/BasicPawn#66]
Would be good to implement new command like 'Decompile' if you open smx via BasicPawn ('Build' replaces with 'Decompile').
This feature can help many people who can't use [Headline's web Lysis](http://headlinedev.xyz/lysis/) due to limitations.

But i think in this case would be also good to implement smx support (like SPEdit does) so you can open smx via BasicPawn and read it's structure (and maybe ASM code?).

**Comment by Timocop** [comment]
I was thinking about this too. However, the C# version of Lysis is heavly outdated (The one that SPEdit uses). The most update-to-date version of lysis would be Peace-Makers version, but its build in Java. (Or Kailos amazing decompiler which is build in C++ but its private :( )

I was thinking about using Peace-Makers version instead of the outdated version. But that also means youll have to install Java on your system. Right now i cant even install the newest Java SDK because the Java website doesnt let me :(.

The official SMX Disassembly library is already build in C# so theres no problem using it.
Those features also will be optional and probably build as plugins.

**Comment by MAGNAT2645** [comment]
Java SDK isn't free as far as I know.
I use AdoptOpenJDK (with Eclipse OpenJ9) instead of Java.

**Comment by Timocop** [comment]
Ah yes JDK not SDK, sorry. Too bad you have to create a Oracle account to download the JDK now. Including phone number, address etc. Sucks.
Ill try AdoptOpenJDK. Im fairly new to building Java with Eclipse.

**Comment by MAGNAT2645** [comment]
There are rumors that it is better not to even try to download JDK from Oracle for free. It's kind of a trap if you're not going to pay. They're asking for your data for a that reason.

**Comment by Timocop** [comment]
I see. Im using OpenJ9 now. Surprisingly Lysis runs super fast with that JVM and i also build Lysis successfully now - finally. Thank you for the tip 👍

**Comment by DosMike** [comment]
Alright... so I was toying around with IKVM and wrote a script [DosMike/lysis-ikvm](/DosMike/lysis-ikvm) that will convert a fork i made into a .net binary.  
My lysis fork just adds a few methods for easier invocation for the whole decompile stuff...

I played around a bit and got BasicPawn to open decompiled smx files with something like this:

```vb
Shared Function loadLysis(filename As String) As String
  Try
    Dim decomp As String = lysis.LibLysis.getDecompiled(filename)
    loadLysis = decomp
  Catch e As java.lang.Exception
    Throw New System.Exception("Unable to decompile")
  End Try
End Function

' In ClassTabControl::OpenFileTab() I added this:
Dim sFileText As String
If (sFile.EndsWith(".smx") Or sFile.EndsWith(".amxx")) Then
  Try
    sFileText = ClassLysisReader.loadLysis(sFile)
    m_Tab(iIndex).m_TextEditor.Document.ReadOnly = True
  Catch e As System.Exception
    sFileText = "// Failed to open File: " & sFile & vbCrLf & "// " & e.Message
  End Try
Else
  sFileText = IO.File.ReadAllText(sFile)
End If
```

Of course special care has to be taken in order to not re-save decompiled sourced over plugins and a load-cursor or something would be nice (for my x-thousand line plugin). 
I haven't really touched VB in years but if you want @Timocop I can send you a crude PR

**Comment by Timocop** [comment]
A Java JIT on a .NET JIT? My lord what has this world become. But it does look indeed promising and does save a lot of time and effort. Amazing job, i will look into this!
I think having Lysis as an optional BasicPawn plugin would be a good idea. Because not much people need to decompile plugins. I'm probably going to modify lysis-java a bit and create a new UI for it too. Such as .NET decompilers ILSpy or RedGates .NET Reflector. If i have the time that is.

**Comment by Timocop** [comment]
Plugin finished.
https://github.com/Timocop/BasicPawn/tree/master/Plugin%20Releases/BasicPawnPluginLysisDecompiler

I've made my own automation code for converting Lysis-Java into .NET. Compiling with IKVM8 seems pretty straight forward.
You can take a look at the automation code here: https://github.com/Timocop/BasicPawn/blob/master/BasicPawnJavaLysisHelper/ClassMain.vb

Thank you DosMike for the amazing idea! I put you in the credits.

**Comment by MAGNAT2645** [comment]
Will you implement Disassembly (view assembly code w/o decompiling) feature in the future? SP(Edit/Code) has this.

**Comment by Timocop** [comment]
Yes i will. In the future i will slowly combine Disassembler and Decompiler. Having both in one window instead. Mimicking .NET Framework Decompilers such as dnSpy or RedGates .NET Reflector. Thats pretty much my goal.
![dnSpy_2021-06-04_00-28-43](https://user-images.githubusercontent.com/22834512/120720263-10410080-c4cc-11eb-9b14-96acbde42a21.png)
