### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by Adrianilloo** [Timocop/BasicPawn#70]
Hi,

I've had to retry on SM coding after some months to make some bugfix. I have downloaded this IDE and it looks great and all; was using SPEdit before. But found two improvable things:

- I have a "standalone" scripting project structure I'm working on (like an external folder from main SM install). I have set up a custom build configuration using this main SM folder for the compiler and include path. Since project is external, I left the field "Output directory" blank, as I would like the .smx file to generate next to the main .sp file, and found this is not possible (error "Compiling failed! Invalid output directory!"). I think the output directory should be same than the current .sp file by default (when empty within configuration), so it makes it convenient when using separate project folders. Would this be possible?

- I reformatted code and the result was pretty good (no major changes from last project's git commit), but found some extra tab indentation on splitted function calls, like this (I'm using tabs):

```
g_hPlayerScoreThinkDelayCVar = CreateConVar("sm_pf_player_score_think_delay", "0.0",
		CVAR_PLAYER_START_THINK_DELAY_DESC, 0, true);
```

Could this indentation use a single tab instead?

Thanks. Great IDE!

**Comment by Timocop** [comment]
Thanks for the feedback!

1\) This could be possible, however, i kinda want to keep the manual paths strict as possible. Since in automatic mode the default compiled output directory is relative to the spcomp.exe binary. Which is going to mimic how compile.exe works and moves the compiled binary into the ``compiled`` folder. Leaving the ``output directory`` empty and moving the ``.smx`` next to the source could be confusing to users. As they could expect the binary inside the ``compiled`` directory instead. But i will have a second thought about that. 

Maybe you may want to use the post-build command-line in the config. It's more flexible anyways. Choose a valid output directory (Your SourceMod ``compiled`` directory inside ``scripting``, normally compile.exe creates that folder; Or use a temporary folder) and use this post-build command-line:
```batch
if "%bp_testing%"=="false" (
move /y "%bp_conf_output%\%bp_source_filename%.smx" "%bp_source_directory%\%bp_source_filename%.smx"
)
```
This will move your ``.smx `` next to your ``.sp`` the argument ``/y`` will overwrite the existing ``.smx`` without asking.

2\) The reason why i choose 2 tabs instead of 1 tab is because multi-line methods will be more distinguishable from normal tab spacing. But i see what you mean and why this could probably be annoying. Maybe i'll an optional setting to change the behaviour.

**Comment by Adrianilloo** [comment]
Thanks. I understand all of this. Will definitely use your proposal instead.

**Comment by Timocop** [comment]
I'll reopen this so i remember working on the tab indentation 😄

**Comment by Timocop** [comment]
I randomly found a bug 1112d9ea5fc6874bc69d40a784bf5d508e9c0c2b in the code reindention. Where as parenthesis where calculated incorrectly and always indented the next line.
Incorrect:
```SourcePawn
PrintToChatAll(
    "Hello World %d",
    GetRandomInt(
        1,
        100
        )
    );
```
Correct:
```SourcePawn
PrintToChatAll(
    "Hello World %d",
    GetRandomInt(
        1,
        100
    )
);
```
Also i removed the initial double indention you mentioned.
