### ISSUE TITLE
Default paths colliding warning.

### ISSUE THREAD

**Issue by GAMMACASE** [Timocop/BasicPawn#73]
I'm getting this warning all the time when I close config settings window even if I don't touch ``Myconf_test1`` or ``Myconf_test2``: 
![image](https://user-images.githubusercontent.com/31375974/80326517-b4746480-8841-11ea-8fdf-39aab453aaf1.png)
Default paths set like so:
``Myconf_test1`` - ``SOMEPATH/scripting``
``Myconf_test2`` - ``SOMEPATH/scripting/test2``
where's SOMEPATH is equal in both configs, and resulting in this warning message. So I'm wondering is this really that big of a deal? can this be somehow suppressed? cuz this is annoying. Or is changing path to somewhere else is the only option?

**Comment by Timocop** [comment]
I've implemented this to warn the user that "Finding the optimal config" might not work correctly due to equal or inherited default paths. There will be a race condition which default path is going to be first since there is not realy a logic for this - for now. For example ``test.sp`` thats inside ``SOMEPATH\scripting\test2`` does also return true when it checks the path against the default path ``SOMEPATH\scripting``. Of course the message box could be better, probably gonna change that soon. 

Right now, to avoid this you'll have to use the 'Known files' option for ``SOMEPATH\scripting\test2`` files which will overwrite any default-path behavior or choose a different directory until i've changed the behavior. Sorry for the inconvenience.

**Comment by Timocop** [comment]
Has been resolved in 87b6e0fb4e5db66bcee5daab008017ba12462a6e. Sub-directories will now work correctly with default paths. If there is a collision between configs, then it will shown in the Information tab instead of a message box.
You can download the dev build if you want to.
