### ISSUE TITLE
[Suggestion] Translation editor

### ISSUE THREAD

**Issue by DosMike** [Timocop/BasicPawn#76]
I thought it would be nice to be able to manage Translation from within the BasicPawn.
It would probably be enough, if it would display a simple table. I'd just like to have a place that tells me when a translation is missing tbh.

| Key | En | De | Es | Fr | Ru | ... |
| ----- | ----- | ----- | ----- | ----- | ----- | ----- |
| hello world | Hello World | Hallo Welt | Hola Mundo | Bonjour le monde | Привет мир | ... |

**Comment by Timocop** [comment]
Sorry for the delay, it's in the workings. This actually takes way longer than i anticipated. Due to researching because everything seems to be undocumented. Especially Valves key values system.
Here are some sneak peaks:
![BasicPawn_2020-07-06_17-02-09](https://user-images.githubusercontent.com/22834512/86608242-8ed6aa80-bfaa-11ea-8951-48f507156b06.png)
![BasicPawn_2020-07-06_17-02-17](https://user-images.githubusercontent.com/22834512/86608252-9007d780-bfaa-11ea-9105-8d33d8379830.png)

**Comment by Timocop** [comment]
Done.
