### ISSUE TITLE
List references can't build connection when file opened via Project tab

### ISSUE THREAD

**Issue by dragokas** [Timocop/BasicPawn#96]
Hi,

I recorded gif here: ![cB8mXunVqy](https://user-images.githubusercontent.com/19956568/120884610-af5d1980-c5ec-11eb-9f6b-8902df2f50a3.gif)

If you open #include files via RMB in "Object Browser" -> Open source files -> Everything OK.

But, when you open one of includes manually via "Project" Tab, BasicPawn can't find the reference (Ctrl + L).

PS. Basic sp has following relationship:
```
#include <sr/convar.sp>
```
Thanks for attention and good luck with that!
Happy to see you actively support it :) Very handy for large projects!

**Comment by Timocop** [comment]
It should not really matter from where you load the file from as long there is a connection between the tabs.
From which file do you load the ``convar.sp`` from? ``l4d_special_rounds.sp`` or a different file?

**Comment by Timocop** [comment]
Looking at your Gif, seems like your ``l4d_special_rounds.sp`` loads its ``convar.sp`` from ``D:\dev\sourcemod\addons\sourcemod\scripting\include\sr\convar.sp`` not from your project file path ``H:\_to_games\left4dead_2\my_mods\gamemode\specialrounds\include\sr\convar.sp``. Its because your custom config aiming ``l4d_special_rounds.sp`` to the include path ``D:\dev\sourcemod\addons\sourcemod\scripting\include``.
``List references`` does work fine, its just two different paths so there is no relationship between main file and include file.

**Comment by dragokas** [comment]
That path is not real.

"D:\dev\sourcemod\addons\sourcemod\scripting\include\sr" is a symlink to "H:\_to_games\left4dead_2\my_mods\gamemode\specialrounds\include\sr"

**Comment by dragokas** [comment]
> From which file do you load the convar.sp from? l4d_special_rounds.sp or a different file?

I'm opening l4d_special_rounds.sp from folder: H:_to_games\left4dead_2\my_mods\gamemode\specialrounds

And I'm just using internal BasicPawn's feature - list of files from "Project" Tab. I didn't add anything manually.
It looks like there is some inconsistency:
 - when he build path to #define sr/*.sp (it took the path relative to compiler's folder)
 - when he build connections in "Project" tab (it took paths next to main sp file)

**Comment by Timocop** [comment]
> That path is not real.
> 
> "D:\dev\sourcemod\addons\sourcemod\scripting\include\sr" is a symlink to "H:_to_games\left4dead_2\my_mods\gamemode\specialrounds\include\sr"

While the path is not real, the path is still different from what ``l4d_special_rounds.sp`` stores in its includes. Which are absolute paths not relative paths. And if you load ``convar.sp`` from different path (even if its a symbolic link) there will be no relationship between those two files. Because the paths itself are still different.

You either open all files via the symbolic link or the original path and not both at the same time otherwise it will not work. Such as your project file. Open it via the original path then it should work (It will open ``convar.sp`` from the original path then).
Sadly there is nothing much i can do here really.
